font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font Mono
    style: Bold Italic

  size: 10
dynamic_title: true
window:
  opacity: 0.95
colors:
  # Default colors
  primary:
    background: "0x191A1A"
    foreground: "0xF1F1E4"

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  # Normal colors
  normal:
    black: "0x191A1A"
    red: "0xE84545"
    green: "0x558E2E"
    yellow: "0xFACC00"
    blue: "0x2494BA"
    magenta: "0xC054BC"
    cyan: "0x2DCDCD"
    white: "0xF1F1E4"

  # Bright colors
  bright:
    black: "0x202122"
    red: "0xF56666"
    green: "0x7EC44F"
    yellow: "0xFFDE0A"
    blue: "0x37AAD1"
    magenta: "0xC76BC4"
    cyan: "0x42D7D4"
    white: "0xF1F1E4"
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 50
    y: 50

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: true
