[colors]
[colors.bright]
black = "0xF8F8F2"
blue = "0x68aee8"
cyan = "0x48C5D6"
green = "0x8fb573"
magenta = "0xD185E0"
red = "0xED5A66"
white = "0xF8F8F2"
yellow = "0xDDC96F"

[colors.normal]
black = "0x1b1c1e"
blue = "0x388BCF"
cyan = "0x37A8B7"
green = "0x658e59"
magenta = "0xbb70d2"
red = "0xde5d68"
white = "0xa7aab0"
yellow = "0xdbb671"

[colors.primary]
background = "0x232326"
foreground = "0xa7aab0"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true
padding = {x = 5, y = 5}
opacity = 1

[env]
TERM="xterm-256color"

