[colors]
[colors.bright]
black = "0x202122"
blue = "0x37AAD1"
cyan = "0x42D7D4"
green = "0x7EC44F"
magenta = "0xC76BC4"
red = "0xF56666"
white = "0xF1F1E4"
yellow = "0xFFDE0A"

[colors.normal]
black = "0x191A1A"
blue = "0x2494BA"
cyan = "0x2DCDCD"
green = "0x558E2E"
magenta = "0xC054BC"
red = "0xE84545"
white = "0xF1F1E4"
yellow = "0xFACC00"

[colors.primary]
background = "0x191A1A"
foreground = "0xF1F1E4"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.95
